/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "background": "#faf8ff",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#497cff",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a1700",
        "on-tertiary-container": "#b87500",
        "on-background": "#131b2e",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed-variant": "#005236",
        "outline": "#76777d",
        "on-secondary-container": "#00714d",
        "primary-container": "#00174b",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "tertiary-fixed": "#ffddb8",
        "on-surface": "#131b2e",
        "tertiary": "#000000",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed-dim": "#ffb95f",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-highest": "#dae2fd",
        "outline-variant": "#c6c6cd",
        "inverse-surface": "#283044",
        "surface-tint": "#0053db",
        "surface-container-high": "#e2e7ff",
        "on-primary": "#ffffff",
        "surface-container": "#eaedff",
        "secondary": "#006c49",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00174b",
        "surface-dim": "#d2d9f4",
        "on-surface-variant": "#45464d",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed": "#6ffbbe",
        "primary": "#000000",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#6cf8bb",
        "on-primary-fixed-variant": "#003ea8",
        "surface": "#faf8ff",
        "secondary-fixed-dim": "#4edea3"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
